Feature comments
ppxxd/java-explore-with-me pull request #3
Opened 2024-11-04 14:48 UTC by ppxxd

added new feature and postman tests

2024-11-05 14:55 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-11-05 14:55 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/comment/service/CommentService.java
> +    Comment checkCommentExistById(Long commentId);
Здесь должны возвращаться dto

2024-11-05 14:55 UTC, mikita95 commented on main-service/src/main/resources/schema.sql
> +    comment_text varchar(2000) not null,
Можно было бы добавить индексы на колонки, по которым часто выполняются запросы, так было бы эффективнее

2024-11-05 22:36 UTC, ppxxd commented on main-service/src/main/java/ru/practicum/comment/service/CommentService.java
> +    Comment checkCommentExistById(Long commentId);
А почему dto? Метод создан для поиска комментария в бд и выбрасывает ошибку если его нет, используется только внутри сервиса. Не понимаю почему нужен dto

2024-11-06 17:03 UTC, mikita95 commented on main-service/src/main/java/ru/practicum/comment/service/CommentService.java
> +    Comment checkCommentExistById(Long commentId);
Если метод используется только в сервисе внутри, то лучше его сделать private, так как это деталь реализации

2024-11-06 17:03 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-11-06 17:04 UTC, merged